#!/bin/bash

## Mac OS X specific aliases
if [ "$(uname)" == "Darwin" ]; then
	# coreutils
	alias ls='gls --color'
	alias du="gdu"
	alias mkdir="gmkdir"
	# Finder options
	alias finder.show_all_files_true="defaults write com.apple.finder AppleShowAllFiles -boolean true && killall Finder"
	alias finder.show_all_files_false="defaults delete com.apple.finder AppleShowAllFiles && killall Finder"
else
	alias ls='ls --color'
fi

alias l='ls -l'
alias ll='ls -la'

alias ds='du -hs'
alias mkdir='mkdir -pv'

## Remove backup files (*~) recursively ##
alias rm.backup="find . -name '*~' -exec rm -vf '{}' +"
alias rm.osx="find . -name '.DS*' -or -name '._.DS*' -exec rm -vf '{}' +"

## SU required commands ##
if [ $UID -ne 0 ]; then
	alias reboot='sudo reboot'
	alias apt-get='sudo apt-get'
	alias iptraf='sudo iptraf'
fi

## Memcached service ##
alias mcdstats='/usr/bin/memcached-tool 10.10.27.11:11211 stats'
alias mcdshow='/usr/bin/memcached-tool 10.10.27.11:11211 display'

## Wget ##
alias wget='wget -c'

## Top memory consuming processes ##
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
 
## Top CPU consuming processes ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## Heroku
alias hk='heroku'
