#!/bin/sh
#
# fluxbox startup-script:

fluxbox -log "~/.fluxbox/log" &
fbpid=$!

sleep 2
{
  xcompmgr -c &
  alttab &
  nitrogen --set-zoom-fill --random ~/.config/wallpapers &
  parcellite &
  dropbox start &
  shutter &
  volumeicon &
  shutter --min_at_startup &
  # gkrellm -w &
} &

wait $fbpid

#exec fluxbox -log "~/.fluxbox/log"
