#!/bin/sh
#
# fluxbox startup-script:

fluxbox -log "~/.fluxbox/log" &
fbpid=$!

sleep 2
{
  # transparency
  #xcompmgr -c &
 
  # wallpaper
  chwp &

  # others
  alttab &
  parcellite &
  dropbox start &
  # shutter &
  volumeicon &
  # shutter --min_at_startup &
  # gkrellm -w &
} &

wait $fbpid

#exec fluxbox -log "~/.fluxbox/log"
