" Vim configuration file

" Plugins {{{1
call plug#begin()
  Plug 'ervandew/supertab'
  Plug 'https://tpope.io/vim/fugitive.git'
  Plug 'jelera/vim-javascript-syntax'
  Plug 'mattn/emmet-vim'
  Plug 'scrooloose/nerdcommenter'
  Plug 'terryma/vim-expand-region'
  Plug 'vim-syntastic/syntastic'
  Plug 'vimwiki/vimwiki'
  Plug 'tpope/vim-surround'
  Plug 'posva/vim-vue'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'cespare/vim-toml'
  Plug 'stephpy/vim-yaml'
  Plug 'ziglang/zig.vim'

  " --- colorschemes ---
  Plug 'pgavlin/pulumi.vim'
  Plug 'arzg/vim-colors-xcode'
  Plug 'wadackel/vim-dogrun'
  Plug 'stillwwater/vim-nebula'
call plug#end()

let mapleader = ","

set nocompatible
set encoding=utf-8
set showcmd                     " display incomplete commands
set ttyfast
set hidden
set title
set undolevels=1000
set history=1000
set ruler

" Folding {{{1
set foldenable
set foldmethod=marker

" vim-wiki {{{1
let g:vimwiki_list = [{'path': '~/notes', 'syntax': 'markdown', 'ext': '.md'}]

" Note taking {{{1
nnoremap <leader>sn :w<CR>:silent exec '!sync-notes'<CR>

" Syntax highlighting {{{1
filetype plugin indent on
filetype plugin on
syntax on

" Show current line and filename {{{1
set modeline
set ls=2

" Backup settings {{{1
set backup
set backupdir=~/.homedir/vim/backup
set directory=~/.homedir/vim/tmp

" Whitespace {{{1
" set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2 expandtab
set autoindent
set backspace=indent,eol,start  " backspace through everything in insert mode

" Searching {{{1
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

" launch incremental search using ripgrep
nmap <c-p> :Rg<CR>

" Others  {{{1
set autoread
set breakindent

" Line numbers {{{1
set number relativenumber

" netrw {{{1
let g:netrw_banner = 0

" Key bindings {{{1
" Move between windows
nmap <tab><tab> <C-w>w

" Replace all alias
nnoremap S :%s//g<Left><Left>

nnoremap <leader>f :find *
nnoremap <leader>s :sfind *
nnoremap <leader>t :tabfind *
nnoremap <leader>v :vert sfind *

" Reload vimrc
nnoremap <leader>r :source ~/.vimrc<CR>

" Toggle word wrap
nnoremap <leader>wr :set wrap!<CR>

" Show invisible characters
nnoremap <leader>l :set list!<CR>

" Move current line up/down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Move current line up/down
nnoremap ¶ :m .+1<CR>==
nnoremap § :m .-2<CR>==
inoremap ¶ <Esc>:m .+1<CR>==gi
inoremap § <Esc>:m .-2<CR>==gi
vnoremap ¶ :m '>+1<CR>gv=gv
vnoremap § :m '<-2<CR>gv=gv

" Insert date
:nnoremap <F5> "=strftime("%Y/%m/%d")<CR>P
:inoremap <F5> <C-R>=strftime("%Y/%m/%d")<CR>


" Filetype specific options {{{1
if has("autocmd")
  " Enable file type detection
  filetype on

  autocmd FileType make        setlocal ts=2 sts=2 sw=2 noexpandtab
  autocmd FileType makefile    setlocal ts=2 sts=2 sw=2 noexpandtab
  autocmd FileType yaml        setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType html        setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css         setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript  setlocal ts=2 sts=2 sw=2 expandtab
  " autocmd FileType javascript  call JavaScriptFold()

  " Treat .rss files as XML
  autocmd BufNewFile,BufRead *.rss setfiletype xml

  " vim-racer
  let g:racer_cmd = '/Users/jr/.cargo/bin/racer'
  augroup Racer
    autocmd!
    autocmd FileType rust nmap <buffer> gd         <Plug>(rust-def)
    autocmd FileType rust nmap <buffer> gs         <Plug>(rust-def-split)
    autocmd FileType rust nmap <buffer> gx         <Plug>(rust-def-vertical)
    autocmd FileType rust nmap <buffer> gt         <Plug>(rust-def-tab)
    autocmd FileType rust nmap <buffer> <leader>gd <Plug>(rust-doc)
  augroup END

endif

if has("vim")
  language en
endif

if has("autocmd")
  autocmd FileType html inoremap ;p <p></p><Space><++><Esc>FpT>i
endif

" CtrlP 
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$|dist/.*'

" Key mapping {{{1
set path=..,**

" Pretty colors {{{1
colorscheme nebula 

" Invisible characters {{{1
set listchars=tab:▸\ ,eol:¬,space:.
highlight NonText guifg=#222222 ctermfg=darkgrey
highlight SpecialKey guifg=#222222 ctermfg=darkgrey
highlight ExtraWhitespace guifg=#222222 ctermfg=darkgrey

