theme = "native"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
format = "{used}/{total} ~{available} free"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5 

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max} max, {average} avg"
chip = "*-isa-*"
#inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 1 
format = "%a %d/%m %R:%S"

#[[block]]
#block = "sound"

#[[block]]
#block = "battery"
#if_command = "test -e /sys/class/power_supply/BAT0"

#[[block]]
#block = "pomodoro"
#length = 25
#break_length = 5
#message = "Take a break!"
#break_message = "Back to work!"
#notifier = "swaynag"
